dataset_bucket: nfwf-tool

vrt:
  continental_us: continental_us.local.vrt
  puerto_rico: puerto_rico.local.vrt
  us_virgin_islands: virgin_islands.local.vrt
  northern_mariana_islands: northern_mariana_islands.local.vrt
  hawaii: hawaii.local.vrt
  american_samoa: american_samoa.local.vrt
  guam: guam.local.vrt

datasets:

  continental_us:
    - name: exposure
      path: CONUS_ExposureIndex_10class_111918.tif
    - name: asset
      path: CONUS_AssetIndex_10class_111918.tif
    - name: threat
      path: CONUS_ThreatIndex_10class_111918.tif
    - name: wildlife
      path: CONUS_CombinedFW_reclassCREST.tif
    - name: aquatic
      path: CONUS_AquaticIndex_clip_111218.tif
    - name: terrestrial
      path: CONUS_TerrestrialIndex_clip_111218.tif
    - name: hubs
      path: CONUS_ResilienceHubs_073020.tif
    - name: crit_infra
      path: CONUS_CritInfra_shift_111518.tif
    - name: crit_facilities
      path: CONUS_CritFac_shift_111918.tif
    - name: pop_density
      path: CONUS_Population_shift_110718.tif
    - name: social_vuln
      path: CONUS_SocVul_shift_110718.tif
    - name: drainage
      path: CONUS_DrainDev_shift_111418.tif
    - name: erosion
      path: CONUS_Erosion_111418.tif
    - name: floodprone_areas
      path: CONUS_Floodprone_shift_111418.tif
    - name: geostress
      path: CONUS_Geostress_shift_111518.tif
    - name: sea_level_rise
      path: CONUS_SLR_shift_110918.tif
    - name: slope
      path: CONUS_Slope_shift_111918.tif
    - name: storm_surge
      path: CONUS_StormSurge_shift_111618.tif

  puerto_rico:
    - name: exposure
      path: PR_ExposureIndex_10class_021120_clip.tif
    - name: asset
      path: PR_AssetIndex_10class_021020_clip.tif
    - name: wildlife
      path: PR_CombinedWildlife_6class_040320.tif
    - name: crit_facilities
      path: PR_CriticalFacilities_v2_clip.tif
    - name: crit_infra
      path: PR_CriticalInfrastructure_v2_clip.tif
    - name: erosion
      path: PR_ErodibleSoils_v2_clip.tif
    - name: floodprone_areas
      path: PR_FloodproneAreas_v2_clip.tif
    - name: impermeable
      path: PR_Impermeable_v2_clip.tif
    - name: landslides
      path: PR_Landslides_v2_clip.tif
    - name: low_areas
      path: PR_LowLyingAreas_v2_clip.tif
    - name: marine
      path: PR_MarineIndex_4class.tif
    - name: pop_density
      path: PR_PopulationDensity_v2_clip.tif
    - name: sea_level_rise
      path: PR_SLR_v2_clip.tif
    - name: social_vuln
      path: PR_SocialVulnerability_v2_clip.tif
    - name: storm_surge
      path: PR_StormSurge_v2_clip.tif
    - name: terrestrial
      path: PR_TerrestrialIndex_4class.tif
    - name: threat
      path: PR_ThreatIndex_10class_021120_clip.tif
    - name: tsunami
      path: PR_Tsunami_v2_clip.tif
    - name: hubs
      path: PR_Combined_Hub_group_July2020.tif

  us_virgin_islands:
    - name: exposure
      path: USVI_ExposureIndex_10class_021220_clip.tif
    - name: threat
      path: USVI_ThreatIndex_10class_021220_clip.tif
    - name: asset
      path: USVI_AssetIndex_10class_021020_clip.tif
    - name: wildlife
      path: USVI_CombinedWildlife_6class_040320.tif
    - name: crit_facilities
      path: USVI_CriticalFacilities_v2_clip.tif
    - name: crit_infra
      path: USVI_CriticalInfrastructure_v2_clip.tif
    - name: erosion
      path: USVI_ErodibleSoils_v2_clip.tif
    - name: floodprone_areas
      path: USVI_FloodproneAreas_v2_clip.tif
    - name: impermeable
      path: USVI_Impermeable_v2_clip.tif
    - name: low_areas
      path: USVI_LowLyingAreas_v2_clip.tif
    - name: marine
      path: USVI_MarineIndex_4class.tif
    - name: pop_density
      path: USVI_PopulationDensity_v2_clip.tif
    - name: sea_level_rise
      path: USVI_SLR_v2_clip.tif
    - name: social_vuln
      path: USVI_SocialVulnerability_v2_clip.tif
    - name: storm_surge
      path: USVI_StormSurge_v2_clip.tif
    - name: terrestrial
      path: USVI_TerrestrialIndex_4class.tif
    - name: hubs
      path: USVI_Combined_Hub_Groups_July2020.tif

  northern_mariana_islands:
    - name: asset
      path: CNMI_Asset_Index_10class.tif
    - name: crit_facilities
      path: CNMI_Critical_Facilities.tif
    - name: crit_infra
      path: CNMI_Critical_Infrastructure.tif
    - name: erosion
      path: CNMI_Erodible_Soils.tif
    - name: exposure
      path: CNMI_Exposure_Index.tif
    - name: floodprone_areas
      path: CNMI_Floodprone_Areas.tif
    - name: impermeable
      path: CNMI_Impermeable_Soils.tif
    - name: low_areas
      path: CNMI_Low_Lying_Areas.tif
    - name: marine
      path: CNMI_Marine_Index.tif
    - name: pop_density
      path: CNMI_Population_Density.tif
    - name: sea_level_rise
      path: CNMI_Sea_Level_Rise.tif
    - name: social_vuln
      path: CNMI_Social_Vulnerability.tif
    - name: terrestrial
      path: CNMI_Terrestrial_Index.tif
    - name: threat
      path: CNMI_Threat_Index_10class.tif
    - name: wave_flooding
      path: CNMI_Wave_Driven_Flooding.tif
    - name: wildlife
      path: CNMI_Wildlife_Index.tif
    - name: hubs
      path: CNMI_Combined_Hub_Group_July2020.tif

  hawaii:
    - name: asset
      path: HI_Asset_Index_10class_102720.tif
    - name: crit_facilities
      path: HI_Crit_Facilities_102720.tif
    - name: crit_infra
      path: HI_Crit_Infrastructure_091020.tif
    - name: exposure
      path: HI_Exposure_Index_10class_102820.tif
    - name: floodprone_areas
      path: HI_Floodprone_Areas_091120.tif
    - name: impermeable
      path: HI_Impermeable_Soils_091120.tif
    - name: landslides
      path: HI_LandslideSuscept_091120.tif
    - name: low_areas
      path: HI_LowLyingAreas_091120.tif
    - name: marine
      path: HI_Marine_Index_4class_102820.tif
    - name: pop_density
      path: HI_Pop_Density_091020.tif
    - name: sea_level_rise
      path: HI_SLRXA_091120.tif
    - name: social_vuln
      path: HI_Soc_Vulnerability_091020.tif
    - name: erosion
      path: HI_Soil_Erodibility_091120.tif
    - name: storm_surge
      path: HI_Storm_Surge_091120.tif
    - name: terrestrial
      path: HI_Terrestrial_Index_4class_102720.tif
    - name: threat
      path: HI_Threat_Index_10class_091120.tif
    - name: tsunami
      path: HI_Tsunami_Evac_091120.tif
    - name: wildlife
      path: HI_Wildlife_Index_6class_102820.tif
    - name: hubs
      path: hi_cores_hubs_111920.tif

  american_samoa:
    - name: asset
      path: AS_Asset_Index_10class_shift_v2-2_LZW.tif
    - name: crit_facilities
      path: AS_C_Facilities_v1_LZW.tif
    - name: crit_infra
      path: AS_C_Infrastructure_v2-2_LZW.tif
    - name: exposure
      path: AS_Exposure_Index_10class_v2-2_LZW.tif
    - name: floodprone_areas
      path: AS_Floodprone_Areas_shift_v1_LZW.tif
    - name: impermeable
      path: AS_Impermeable_Surfaces_shift_v1_LZW.tif
    - name: slope
      path: AS_Slope_resample_v1_LZW.tif
    - name: marine
      path: AS_Marine_Index_4class_v2_LZW.tif
    - name: pop_density
      path: AS_PopDensity_v1_LZW.tif
    - name: sea_level_rise
      path: AS_SLR_shift_v1_LZW.tif
    - name: social_vuln
      path: AS_SocVul_v1_LZW.tif
    - name: terrestrial
      path: AS_Terrestrial_Index_4class_v2_LZW.tif
    - name: wave_flooding
      path: AS_WaveDriven_Flooding_shift_v1_LZW.tif
    - name: threat
      path: AS_Threat_Index_10class_v2_LZW.tif
    - name: tsunami
      path: AS_Tsunami_LZW.tif
    - name: wildlife
      path: AS_Wildlife_Index_6class_v2_LZW.tif
    - name: hubs
      path: as_hubs_hexes_dissolve_8.tif
    - name: erosion
      path: AS_Erodible_Soils_shift_v1_LZW.tif

  guam:
    - name: asset
      path: GU_Asset_Index_10class_v2.tif
    - name: crit_facilities
      path: GU_C_Facilities_v2.tif
    - name: crit_infra
      path: GU_C_Infrastructure_v2.tif
    - name: erosion
      path: GU_Erodible_Soils_shift_v1.tif
    - name: exposure
      path: GU_Exposure_Index_10class_v2.tif
    - name: floodprone_areas
      path: GU_Floodprone_Areas_shift_v1.tif
    - name: hubs
      path: gu_hubs_hexes_dissolve.tif
    - name: impermeable
      path: GU_Impermeable_Soils_shift_v1.tif 
    - name: landslides
      path: GU_Landslides_merge.tif
    - name: marine
      path: GU_Marine_Index_4class_v2.tif
    - name: pop_density
      path: GU_PopDensity_v1.tif
    - name: sea_level_rise
      path: GU_SLR_shift_v1.tif
    - name: slope
      path: GU_Slope_v1.tif
    - name: social_vuln
      path: GU_Social_Vulnerability_v1.tif
    - name: terrestrial
      path: GU_Terrestrial_index_4class_v3.tif
    - name: threat
      path: GU_Threat_Index_10class_v2.tif
    - name: wave_flooding
      path: GU_WaveDrivenFlooding_shift_v1.tif 
    - name: wildlife
      path: GU_Wildlife_Index_6class_.tif
    - name: tsunami
      path: GU_tsunami.tif
    - name: wave_exposure
      path: wave_exposure_5class_proj.tif


test:
  points:
    continental_us:
      lat: 35.89
      lng: -79.45
    puerto_rico:
      lat: 18.28
      lng: -66.42
    us_virgin_islands:
      lat: 17.77
      lng: -64.79
    northern_mariana_islands:
      lat: 15.203017
      lng: 145.72
  polygons:
    continental_us: '{"type":"FeatureCollection","name":"test-ar","features":[{"type":"Feature","properties":{"id":"conus_poly"},"geometry":{"type":"Polygon","coordinates":[[[-80.01149654388428,32.887677980874706],[-80.01911401748657,32.88337138447869],[-80.01553058624268,32.87764094428261],[-80.00417947769165,32.882578515468],[-80.01149654388428,32.887677980874706]]]}}]}'
    puerto_rico: '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"id":"puerto_rico_poly"},"geometry":{"type":"Polygon","coordinates":[[[-66.19537353515625,18.374075820054482],[-66.2750244140625,18.312810846425442],[-66.15966796875,18.272390159624983],[-66.08963012695312,18.380592091462194],[-66.2091064453125,18.4209874751591],[-66.19537353515625,18.374075820054482]]]}}]}'
    us_virgin_islands: '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"id":"us_virgin_islands_poly"},"geometry":{"type":"Polygon","coordinates":[[[-64.78466033935547,17.768958359342278],[-64.80199813842773,17.73854993679923],[-64.75187301635742,17.729230192705025],[-64.7398567199707,17.756534036838417],[-64.78260040283203,17.77402592723689],[-64.78466033935547,17.768958359342278]]]}}]}'
    northern_mariana_islands: '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"id":"cnmi_poly"},"geometry":{"type":"Polygon","coordinates":[[[145.77878952026367,15.228125499059319],[145.77394008636475,15.225475339228003],[145.7759141921997,15.221707085774053],[145.78372478485107,15.222328231095478],[145.78308105468747,15.226013655644088],[145.77878952026367,15.228125499059319]]]}}]}'

